# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caliDistortionWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        Form.setMaximumSize(QtCore.QSize(640, 480))
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 611, 461))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.bUndo = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bUndo.setMinimumSize(QtCore.QSize(64, 64))
        self.bUndo.setMaximumSize(QtCore.QSize(64, 64))
        self.bUndo.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bUndo.setIcon(icon)
        self.bUndo.setIconSize(QtCore.QSize(56, 56))
        self.bUndo.setObjectName("bUndo")
        self.gridLayout.addWidget(self.bUndo, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 0, 1, 1, 1)
        self.bExit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bExit.setMinimumSize(QtCore.QSize(64, 64))
        self.bExit.setMaximumSize(QtCore.QSize(64, 64))
        self.bExit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bExit.setIcon(icon1)
        self.bExit.setIconSize(QtCore.QSize(56, 56))
        self.bExit.setObjectName("bExit")
        self.gridLayout.addWidget(self.bExit, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem2, 2, 0, 1, 1)
        self.bSample = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.bSample.setMinimumSize(QtCore.QSize(64, 64))
        self.bSample.setMaximumSize(QtCore.QSize(64, 64))
        self.bSample.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/foto.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bSample.setIcon(icon2)
        self.bSample.setIconSize(QtCore.QSize(56, 56))
        self.bSample.setObjectName("bSample")
        self.gridLayout.addWidget(self.bSample, 3, 2, 1, 1)
        self.lSamples = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lSamples.setObjectName("lSamples")
        self.gridLayout.addWidget(self.lSamples, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.gvCamera = QtWidgets.QGraphicsView(Form)
        self.gvCamera.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.gvCamera.setMaximumSize(QtCore.QSize(640, 480))
        self.gvCamera.setObjectName("gvCamera")
        self.gvCamera.raise_()
        self.gridLayoutWidget.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lSamples.setText(_translate("Form", "0/15"))
import icons_rc
