# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caliOffset_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalibrationOffsetTestWindow(object):
    def setupUi(self, CalibrationOffsetTestWindow):
        CalibrationOffsetTestWindow.setObjectName("CalibrationOffsetTestWindow")
        CalibrationOffsetTestWindow.resize(640, 480)
        self.label = QtWidgets.QLabel(CalibrationOffsetTestWindow)
        self.label.setGeometry(QtCore.QRect(200, 50, 240, 40))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.bExit = QtWidgets.QPushButton(CalibrationOffsetTestWindow)
        self.bExit.setGeometry(QtCore.QRect(580, 10, 50, 50))
        self.bExit.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bExit.setIcon(icon)
        self.bExit.setIconSize(QtCore.QSize(50, 50))
        self.bExit.setFlat(True)
        self.bExit.setObjectName("bExit")
        self.bDecline = QtWidgets.QPushButton(CalibrationOffsetTestWindow)
        self.bDecline.setGeometry(QtCore.QRect(220, 200, 56, 56))
        self.bDecline.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/undo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bDecline.setIcon(icon1)
        self.bDecline.setIconSize(QtCore.QSize(56, 56))
        self.bDecline.setFlat(True)
        self.bDecline.setObjectName("bDecline")
        self.bAccept = QtWidgets.QPushButton(CalibrationOffsetTestWindow)
        self.bAccept.setGeometry(QtCore.QRect(364, 200, 56, 56))
        self.bAccept.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/ok.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bAccept.setIcon(icon2)
        self.bAccept.setIconSize(QtCore.QSize(56, 56))
        self.bAccept.setFlat(True)
        self.bAccept.setObjectName("bAccept")

        self.retranslateUi(CalibrationOffsetTestWindow)
        QtCore.QMetaObject.connectSlotsByName(CalibrationOffsetTestWindow)

    def retranslateUi(self, CalibrationOffsetTestWindow):
        _translate = QtCore.QCoreApplication.translate
        CalibrationOffsetTestWindow.setWindowTitle(_translate("CalibrationOffsetTestWindow", "Offset Calibration Test"))
        self.label.setText(_translate("CalibrationOffsetTestWindow", "Test: Runde Buttons"))
import icons_rc
