# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/caliSelectWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(640, 480)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cbSettings = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.cbSettings.setEnabled(False)
        self.cbSettings.setObjectName("cbSettings")
        self.verticalLayout.addWidget(self.cbSettings, 0, QtCore.Qt.AlignHCenter)
        self.cbGeometric = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.cbGeometric.setEnabled(False)
        self.cbGeometric.setObjectName("cbGeometric")
        self.verticalLayout.addWidget(self.cbGeometric, 0, QtCore.Qt.AlignHCenter)
        self.cbSize = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.cbSize.setEnabled(False)
        self.cbSize.setObjectName("cbSize")
        self.verticalLayout.addWidget(self.cbSize, 0, QtCore.Qt.AlignHCenter)
        self.cbOffset = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.cbOffset.setEnabled(False)
        self.cbOffset.setObjectName("cbOffset")
        self.verticalLayout.addWidget(self.cbOffset, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.bDevice = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bDevice.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.bDevice.setObjectName("bDevice")
        self.verticalLayout_2.addWidget(self.bDevice, 0, QtCore.Qt.AlignHCenter)
        self.bCDistortion = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bCDistortion.setObjectName("bCDistortion")
        self.verticalLayout_2.addWidget(self.bCDistortion, 0, QtCore.Qt.AlignHCenter)
        self.bCPerspective = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bCPerspective.setObjectName("bCPerspective")
        self.verticalLayout_2.addWidget(self.bCPerspective, 0, QtCore.Qt.AlignHCenter)
        self.bCOffset = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bCOffset.setMinimumSize(QtCore.QSize(0, 0))
        self.bCOffset.setObjectName("bCOffset")
        self.verticalLayout_2.addWidget(self.bCOffset, 0, QtCore.Qt.AlignHCenter)
        self.bCTest = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bCTest.setObjectName("bCTest")
        self.verticalLayout_2.addWidget(self.bCTest, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.bBack = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bBack.setMaximumSize(QtCore.QSize(200, 50))
        self.bBack.setObjectName("bBack")
        self.verticalLayout_2.addWidget(self.bBack, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(68, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.cbSettings.setText(_translate("Form", "CheckBox"))
        self.cbGeometric.setText(_translate("Form", "CheckBox"))
        self.cbSize.setText(_translate("Form", "CheckBox"))
        self.cbOffset.setText(_translate("Form", "CheckBox"))
        self.bDevice.setText(_translate("Form", "Device"))
        self.bCDistortion.setText(_translate("Form", "Distortion"))
        self.bCPerspective.setText(_translate("Form", "Perspective"))
        self.bCOffset.setText(_translate("Form", "Offset"))
        self.bCTest.setText(_translate("Form", "Test"))
        self.bBack.setText(_translate("Form", "Back"))
