# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(640, 457))
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 461))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.bCameraSetup = QtWidgets.QPushButton(self.layoutWidget)
        self.bCameraSetup.setMinimumSize(QtCore.QSize(0, 50))
        self.bCameraSetup.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bCameraSetup.setObjectName("bCameraSetup")
        self.verticalLayout.addWidget(self.bCameraSetup, 0, QtCore.Qt.AlignHCenter)
        self.bMCUSetup = QtWidgets.QPushButton(self.layoutWidget)
        self.bMCUSetup.setMinimumSize(QtCore.QSize(0, 50))
        self.bMCUSetup.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bMCUSetup.setObjectName("bMCUSetup")
        self.verticalLayout.addWidget(self.bMCUSetup, 0, QtCore.Qt.AlignHCenter)
        self.bCncMode = QtWidgets.QPushButton(self.layoutWidget)
        self.bCncMode.setMinimumSize(QtCore.QSize(0, 50))
        self.bCncMode.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bCncMode.setObjectName("bCncMode")
        self.verticalLayout.addWidget(self.bCncMode, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.bExit = QtWidgets.QPushButton(self.layoutWidget)
        self.bExit.setMinimumSize(QtCore.QSize(0, 50))
        self.bExit.setMaximumSize(QtCore.QSize(200, 16777215))
        self.bExit.setObjectName("bExit")
        self.verticalLayout.addWidget(self.bExit, 0, QtCore.Qt.AlignHCenter)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem2)
        self.cbCamera = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbCamera.setEnabled(False)
        self.cbCamera.setObjectName("cbCamera")
        self.verticalLayout.addWidget(self.cbCamera, 0, QtCore.Qt.AlignHCenter)
        self.cbMCU = QtWidgets.QCheckBox(self.layoutWidget)
        self.cbMCU.setEnabled(False)
        self.cbMCU.setObjectName("cbMCU")
        self.verticalLayout.addWidget(self.cbMCU, 0, QtCore.Qt.AlignHCenter)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bCameraSetup.setText(_translate("MainWindow", "Setup Cam"))
        self.bMCUSetup.setText(_translate("MainWindow", "Setup MCU"))
        self.bCncMode.setText(_translate("MainWindow", "CNC Mode"))
        self.bExit.setText(_translate("MainWindow", "EXIT"))
        self.cbCamera.setText(_translate("MainWindow", "CheckBox"))
        self.cbMCU.setText(_translate("MainWindow", "CheckBox"))
