# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settingsWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# This file has been archived: the generated UI was moved to `settingsWin.kws`.
# The .kws file is for archival purposes and isn't importable by Python.
# Keep this small stub so tools that open the file won't fail.

"""ARCHIVED: settingsWin UI

The original generated UI implementation lives in `settingsWin.kws`.
If you need to regenerate or re-enable it, copy the contents back to
`settingsWin.py` or run pyuic5 on `ui/settingsWin.ui`.
"""

# Intentionally empty stub.
