# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'caliDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CalibrationDialog(object):
    def setupUi(self, CalibrationDialog):
        CalibrationDialog.setObjectName("CalibrationDialog")
        CalibrationDialog.resize(400, 350)
        CalibrationDialog.setMinimumSize(QtCore.QSize(400, 350))
        CalibrationDialog.setMaximumSize(QtCore.QSize(400, 350))
        CalibrationDialog.setStyleSheet("QWidget#CalibrationDialog {\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QLabel#lTitle {\n"
"    font-size: 13pt;\n"
"    font-weight: bold;\n"
"    color: #2196F3;\n"
"}\n"
"\n"
"QLabel#lProgress {\n"
"    font-size: 10pt;\n"
"    color: #333;\n"
"    padding: 5px;\n"
"    line-height: 1.3;\n"
"}\n"
"\n"
"QPushButton {\n"
"    min-width: 80px;\n"
"    min-height: 35px;\n"
"    border-radius: 5px;\n"
"    font-size: 11pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QPushButton#bAccept {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#bAccept:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"\n"
"QPushButton#bAccept:disabled {\n"
"    background-color: #cccccc;\n"
"    color: #666666;\n"
"}\n"
"\n"
"QPushButton#bCancel {\n"
"    background-color: #f44336;\n"
"    color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton#bCancel:hover {\n"
"    background-color: #da190b;\n"
"}\n"
"\n"
"QPushButton#bCancel:disabled {\n"
"    background-color: #cccccc;\n"
"    color: #666666;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(CalibrationDialog)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lTitle = QtWidgets.QLabel(CalibrationDialog)
        self.lTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.lTitle.setObjectName("lTitle")
        self.verticalLayout.addWidget(self.lTitle)
        spacerItem = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.lProgress = QtWidgets.QLabel(CalibrationDialog)
        self.lProgress.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lProgress.setWordWrap(True)
        self.lProgress.setObjectName("lProgress")
        self.verticalLayout.addWidget(self.lProgress)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.bCancel = QtWidgets.QPushButton(CalibrationDialog)
        self.bCancel.setObjectName("bCancel")
        self.horizontalLayout.addWidget(self.bCancel)
        self.bAccept = QtWidgets.QPushButton(CalibrationDialog)
        self.bAccept.setObjectName("bAccept")
        self.horizontalLayout.addWidget(self.bAccept)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(CalibrationDialog)
        QtCore.QMetaObject.connectSlotsByName(CalibrationDialog)

    def retranslateUi(self, CalibrationDialog):
        _translate = QtCore.QCoreApplication.translate
        CalibrationDialog.setWindowTitle(_translate("CalibrationDialog", "Calibration Progress"))
        self.lTitle.setText(_translate("CalibrationDialog", "Processing Calibration"))
        self.lProgress.setText(_translate("CalibrationDialog", "Processing photos..."))
        self.bCancel.setText(_translate("CalibrationDialog", "Cancel"))
        self.bAccept.setText(_translate("CalibrationDialog", "Accept"))
