# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        MainWindow.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 641, 481))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tvSettings = QtWidgets.QTreeWidget(self.horizontalLayoutWidget)
        self.tvSettings.setObjectName("tvSettings")
        self.tvSettings.headerItem().setText(0, "1")
        self.tvSettings.header().setVisible(False)
        self.verticalLayout.addWidget(self.tvSettings)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 20)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bOk = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bOk.setMinimumSize(QtCore.QSize(50, 50))
        self.bOk.setObjectName("bOk")
        self.horizontalLayout_2.addWidget(self.bOk)
        self.bCancel = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.bCancel.setMinimumSize(QtCore.QSize(50, 50))
        self.bCancel.setObjectName("bCancel")
        self.horizontalLayout_2.addWidget(self.bCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gvCamera = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.gvCamera.setMinimumSize(QtCore.QSize(0, 0))
        self.gvCamera.setMaximumSize(QtCore.QSize(5000, 5000))
        self.gvCamera.setObjectName("gvCamera")
        self.horizontalLayout.addWidget(self.gvCamera)
        self.horizontalLayout.setStretch(1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bOk.setText(_translate("MainWindow", "OK"))
        self.bCancel.setText(_translate("MainWindow", "back"))
